name: Trigger deployment to production

on:
  push:
    branches:
      - main

jobs:
  deploy-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger workflow
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GH_PAT }}
          repository: delta-hq/openblocklabs-airflow-mwaa
          event-type: trigger-workflow
          client-payload: '{"ref": "main", "ENV": "prod"}'
